### ISSUE TITLE
Replace hardcoded urls in .well-known with placeholders who are obviously placeholders 

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/DIDroom_microservices#131]
# Problem
Currently in the .well-known files, there are some URLs that can be confusing for the users, as well as an a public key that can't work. 

Therefore, **for each of the .well-known files**:

- [ ]  replace `https://issuer1.zenswarm.forkbomb.eu` with `url-of-credential-issuer` and replace the value of **kid** with `issuer-public-key`
- [ ] replace `https://authz-server1.zenswarm.forkbomb.eu` with `url-of-authz-server` and replace the value of **kid** with `authz-server-public-key`
- [ ] replace `https://relying-party1.zenswarm.forkbomb.eu` with `url-of-relying-party` and replace the value of **kid** with `relying-party-public-key`

- [ ] When the above is done, update the tests accordingly.

**Comment by puria** [comment]
It would be very helpful to have a small check that displays a HUGE warning box when these values are not replaced, alerting the user that the `.well-known` configuration is broken.

This feature would save a significant amount of debugging time. When it comes time to implement this, we can discuss the details, perhaps by using an `.autorun` script.
