### ISSUE TITLE
Credential Issuance from issuer missing the kid 

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/DIDroom_microservices#144]
Currently the credential issuer (and probably also other microservices) will work even if the the "kid" in the .well-know is empty. This should be prevented.

I believe that we need a .well-know validation too, built in the microservices, possible as a part of DIDimo (@puria )

A good way to prevent this could be to add a json.schema conformance test of the .well-known(s) - the json.schemas can be initially produced from our valid .well-known. This may require to write some code in NCR

**Comment by matteo-cristino** [comment]
This will not prevent the microservice to go up, but will make the well-known unreachable. Thus a simple get can be added to the makefile (?) to try an see if the wk is reachable, if not then stop the service, otherwise everything should be good!

**Comment by andrea-dintino** [comment]
The Kid can be missing for multiple reasons, which should be listed in the error message, including (maybe there are more!):
- The DID has not been stored in the .well-known
- The DID (and DID document) has not been registered by the online service
- The pubkeys used in the DID have not been generated
- The secret keys have not been generated
