### ISSUE TITLE
make deepclean -> git restore doesn't work

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/DIDroom_microservices#169]
This line: https://github.com/ForkbombEu/DIDroom_microservices/blob/main/Makefile#L164

Returns "this is not a git repo"

**Comment by matteo-cristino** [comment]
This happen when you download the micorservice from the dashboard? Or also when cloning them?

**Comment by matteo-cristino** [comment]
solve in #171, deepclean now is not printed out on `make help`, it is just a dev utility
