### ISSUE TITLE
make up does sometimes not create the secret keys

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/DIDroom_microservices#170]
On a Ubuntu 22.04 (clean install), a non-root user executed _make_ and _make up_ and while the microservices were launched, the secret keys were not created. 

On top of this, it appears that a ghost AAA is added to a path? :-O   https://gyazo.com/6f82ee596e14ea5901a6dbfc52ee5e1b

Also it seems that sometimes (!) wk.sh is not executable

This requires 3 intervention: 
1) make sure that wk.sh executable
2) Makefile should check that the keys where actually created (and/or if they exist), if not it should exit with an error
3) This issue https://github.com/ForkbombEu/DIDroom_microservices/issues/144

**Comment by matteo-cristino** [comment]
Do you have the logs of the key creation failure?
