### ISSUE TITLE
If ncr present check version is the one correct, otherwise download it again

### ISSUE THREAD

**Issue by matteo-cristino** [ForkbombEu/DIDroom_microservices#189]

**Comment by puria** [comment]
you can make a mise plugin if you have time, also for zencode-exec, slangroom-exec so you just update a .tool-version file

**Comment by puria** [comment]
https://github.com/asdf-vm/asdf/blob/master/docs/plugins/create.md

**Comment by matteo-cristino** [comment]
will for sure look into that 🥇
