### ISSUE TITLE
Create microservices flow, implement "identity" and "announce"

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/DIDroom_microservices#34]
we have defined the key and DID creation flow which will ultimately be identical to "identity" and "announce" of the old Zenswarm (so we can copy and re-implement in Slanroom what little there was in Restroom).

1) the user who wants to deploy the microservices must originally have a domain and a server on which to deploy DIDroom_microservices.

2) the user logs in to Signroom/DIDroom, clicks on "Microservices" (currently "Servers") and starts adding the authz_server, credential_issuer and relying_party, at this stage he adds the domain (which at this moment will be empty). 
Notes:
   - In Signroom/DIDroom, under the "Add microservice" window, there should also be an "import .well-known" button (we'll look at this later).
   - When the user adds the domain, the text field should do something like auto-complete so it appends in gray  /authz_server/ if setting up an authorization server, /credential_issuer/ (if setting up a credential issuer) and /relying_party/ if setting up a relying party (see point 4 to get some context)

3) the user then creates his first "Credential issuance", using a template or creating a new one. When he's done, the user clicks "download", the page downloads DIDroom_microservices.zip

4) This DIDroom_microservices.zip will be uploaded and unzipped to the server(s) the domain points to. In the future we should handle the case that the microservices are on different machines, but now we don't worry about it and we assume that everything goes on the same machine (right @puria_dyne?), see note to Giovanni in point 2)

5) at this point the user logs in via SSH to the machine and does, once for each microservice (!!!):

* **make identity**: this creates the sks and puts them somewhere (see Zenswarm)

and then

* **make announce**: this creates the DID Document and asks our service to register them. When the service responds, the DID is put somewhere near the private keys AND ALSO in the related .well-know

6) at this point, the user goes back to Signroom, goes back to "Credential Issuance", produces a QR Code and the wallet should be able to get a credential.

**Comment by puria** [comment]
Very good. Except point 5, the implementation details:

the contracts should go under the `.autorun` folder with the `run once` option, we do not care if it's for each server, means we need three contract in place of one. No prob ;)

**Comment by matteo-cristino** [comment]
`step 5` should have been done in #51. Not merged yet since it will break tests in `mobile_zencode` repo, as soon as this will be fixed then it could be merged

**Comment by andrea-dintino** [comment]
Obsolete, replaced by current auto-deployment.
