### ISSUE TITLE
PAR input data format

### ISSUE THREAD

**Issue by matteo-cristino** [ForkbombEu/DIDroom_microservices#64]
As stated by [rfc9126](https://datatracker.ietf.org/doc/html/rfc9126)
```
The pushed authorization request endpoint is an HTTP API at the authorization
server that accepts HTTP POST requests with parameters in the HTTP request
message body using the application/x-www-form-urlencoded format.
```
the data in input to PAR should be of the form
```
 &response_type=code
 &client_id=CLIENT1234&state=duk681S8n00GsJpe7n9boxdzen
 &redirect_uri=https%3A%2F%2Fclient.example.org%2Fcb
 &client_assertion_type=
  urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer
 &client_assertion=eyJraWQiOiI0MiIsImFsZyI6IkVTMjU2In0.eyJpc3MiOiJDTE
  lFTlQxMjM0Iiwic3ViIjoiQ0xJRU5UMTIzNCIsImF1ZCI6Imh0dHBzOi8vc2VydmVyL
  mV4YW1wbGUuY29tIiwiZXhwIjoxNjI1ODY4ODc4fQ.Igw8QrpAWRNPDGoWGRmJumLBM
  wbLjeIYwqWUu-ywgvvufl_0sQJftNs3bzjIrP0BV9rRG-3eI1Ksh0kQ1CwvzA
```
not a json.
The question is who should handle the conversion between the varius form of input to json? ncr or slangroom?

**Comment by puria** [comment]
yes formencoded is the correct format... it's unfortunate known... I forgot to add it to the metadata! Thanks that you reminded me!

So, should do it... meand ncr should accept just `application/x-www-form-urlencoded` and pass it to contract just if the header is correct.

Then in slangroom you can have a sentence to do the parsing, and validate that the format also is not a application/json.

**Comment by matteo-cristino** [comment]
I am thinking about it, but slangroom data in input must be a json and now it is a string thus ncr should also at least set a certain variable with this value to be taken in input from slangroom/zencode

**Comment by matteo-cristino** [comment]
It seems that this encoding format is used also for the /authorize and /token endpoint when doing POST [rfc6749](https://datatracker.ietf.org/doc/html/rfc6749)

**Comment by andrea-dintino** [comment]
@matteo-cristino we do have **application/x-www-form-urlencoded format.** already, we just need to update the Zencode (client/server side)
