### ISSUE TITLE
Missing claims in credentials

### ISSUE THREAD

**Issue by RebeccaSelvaggini** [ForkbombEu/DIDroom_microservices#66]
The credential we return from the credential_issuer [credential endpoint](https://github.com/ForkbombEu/DIDroom_microservices/blob/main/credential_issuer/credential.zen) contains only the claims filled by the holder (output of the introspection endpoint) and the _sd_alg claim. Decoding the payload of the sd-jwt you get something like:
```json
       {
            "_sd": [
               "nvPm4n5BGvL_Gy1u4VXa_eJ9Z_GJq1CsltZ-pnWrHu8",
               "jrJd3cmvIcSnYOZYp0OQox6ska35U--jMX8NiDk-D-4",
               "ygCe49uk9b0A8gWy7qctijLix0ibXW7KKK7U-JsZt58"
            ],
            "_sd_alg": "sha-256"
         }
```

The final credential should contain also the following claims:
- iss: url of the credential_issuer
- iat: (=IssuedAt) current timestamp 
- exp: expiration date
- type: name of the credential type (es. Auth1)

These claims should be computed and added to the dictionary holder_claim in credential.zen before [line 38](https://github.com/ForkbombEu/DIDroom_microservices/blob/main/credential_issuer/credential.zen#L38).
In the end the payload of the credential should look like: 
```json
       {
            "_sd": [
               "nvPm4n5BGvL_Gy1u4VXa_eJ9Z_GJq1CsltZ-pnWrHu8",
               "jrJd3cmvIcSnYOZYp0OQox6ska35U--jMX8NiDk-D-4",
               "ygCe49uk9b0A8gWy7qctijLix0ibXW7KKK7U-JsZt58"
            ],
            "_sd_alg": "sha-256",
            "exp": 1711571651,
            "iat": 1711471651,
            "iss": "http://issuer_example.org",
            "type": "Auth1"
         }
```

**Comment by matteo-cristino** [comment]
Add also `sub` and `nbf`

**Comment by matteo-cristino** [comment]
done in #74
