### ISSUE TITLE
Authorize endpoint response is not compliant with rfc6749

### ISSUE THREAD

**Issue by matteo-cristino** [ForkbombEu/DIDroom_microservices#67]
As stated in [rfc6749 section-4.1.2](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2) the `Authorization Response` should be the redirect_uri on which we happend the `code` and `state` using the "application/x-www-form-urlencoded" format and status always set to 302.

For example given the `Authorization Request`:
```
GET /authorize?response_type=code&client_id=s6BhdRkqt3&state=xyz
        &redirect_uri=https%3A%2F%2Fclient%2Eexample%2Ecom%2Fcb HTTP/1.1
Host: server.example.com
```
The `Authorization Response` should be
```
HTTP/1.1 302 Found
Location: https://client.example.com/cb?code=SplxlOBeZQQYbYS6WxSbIA&state=xyz
```
In case of error
```
HTTP/1.1 302 Found
Location: https://client.example.com/cb?error=access_denied&state=xyz
```
Note: `access_denied` is just a type of the multiple errors that can returned

**Comment by matteo-cristino** [comment]
I missed the main question I wanted to ask 🤖 with ncr we can not still set a response header right? Moreover, from the other side, slangroom when does a POST does not read the response header right?

**Comment by andrea-dintino** [comment]
@matteo-cristino we do have **application/x-www-form-urlencoded format.** already, we just need to update the Zencode (client/server side)

**Comment by matteo-cristino** [comment]
Not related to `application/x-www-form-urlencoded format` directly, but to the fact that authorize page should return a redirection response.
