### ISSUE TITLE
Makefile error on first run

### ISSUE THREAD

**Issue by puria** [ForkbombEu/DIDroom_microservices#82]
```sh
make -v
GNU Make 4.4.1
```

on new cloned repo when run make up gives me

```
ncr                         100%[========================================>] 143.78M  1.51MB/s    in 1m 44s  
📦 Setup is done!
Makefile:48: *** "Unknown service: all. Known service are: authz_server, credential_issuer, relying_party or all".  Stop.
```

**Comment by puria** [comment]
announce: SERVICE ?= all

could be not read in announce target... (dunno why)

obviously when I change it 
`SERVICE ?= all`
defined globally it works

**Comment by matteo-cristino** [comment]
Should be resolve in #84, the problem was that `ifeq` and `ifneq` are evaluated at Makefile reading, thus the SERVICE variable was always unset at that time.
