### ISSUE TITLE
On top of the Makefile, make sure that the needed commands are installed (wget jq git)

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/DIDroom_microservices#89]
Not sure what is the best strategy here, but the user should get feedback if some of the commands are missing, with instructions to what to do, The commands needed are: **make wget jq git**

I think that make we should take it for granted, but we can check the others.

**Comment by puria** [comment]
`make` is already installed if you are able to run a Makefile ;p

the checks for `wget` it's already in there, see:

https://github.com/ForkbombEu/DIDroom_microservices/blob/main/Makefile#L18-L23

that is the unique tool needed to run the services!

`jq` and `npx` are needed for testing, not needed to run the services, no installation pollution is needed, unless you want to run the test suites. we can add the checks of the tools inside the `make test` though!

@matteo-cristino to check a list of tools you want to take inspiration from here:

https://github.com/ForkbombEu/DIDroom/blob/main/docs/.installation_instructions/Makefile#L6-L8
